### PR TITLE
Edit workflow inputs and restructure workflow view

### PR DESCRIPTION
**Pull request by jeffbaumes**
Also removing cruft from experimental "Workflows" app which had confusing file names, and reworking d3-based monolithic workflow view with several Bootstrap/jade views.

Still todo:
* [x] Make task update from Girder work
* [x] Make editing workflow inputs/outputs/tasks work
* [x] Add in code for text wrapping
* [x] Tasks in workflow should have names and no ids
* [x] Make sure workflow visualizations work
* [x] Create workflow input
* [x] Delete workflow connections in edit mode
* [x] Do not display fixed inputs

### CODE REVIEW

**Comment by jeffbaumes** [comment]
This monster branch is ready for review.

@zackgalbreath when you have a few minutes please spend 10 or 15 minutes putting this branch through its paces in regards to workflows and analyses (creating, updating, deleting steps and connections). Also try to create fixed workflow inputs using the pencil edit icon - they should not appear in the setup and run dialog and should be fixed to the default value.

@zachmullen if you could glance over the new code that would be great. Overall netting a few hundred lines but this adds the workflow input/output edit functionality.

**Comment by zackgalbreath** [comment]
Creating workflows, updating steps, and fixing inputs (with the pencil icon) all worked fine for me.  Let me know if there's any other features you'd like me to manually test on this branch.

**Comment by curtislisle** [comment]
Cool!  Looking forward !

**Comment by jeffbaumes** [comment]
Ok looks like we're ready to merge this guy. I'll also update arbor.kitware.com if you want to take it for a spin @curtislisle

**Comment by jeffbaumes** [comment]
Ok this is live and at a glance does not appear to be broken.

**Pull request merged**
