### PR TITLE
Disable romanesco auth requirement for vagrant box

### PR DESCRIPTION
**Pull request by zachmullen**
Additionally,

* Use the pip installed version of girder_client
* Made the provisioning script more idempotent by using ansible's builtin symlink support rather than doing them manually.

### CODE REVIEW

**Comment by zachmullen** [comment]
ping @jeffbaumes @curtislisle

**Comment by jeffbaumes** [comment]
Got this error just now on vagrant up:

```
TASK: [girder | install easy mode analyses and disable auth requirement for romanesco] ***
failed: [default] => {"changed": true, "cmd": ["python", "easymode-setup.py", "/vagrant/ArborWebApps"], "delta": "0:00:00.502523", "end": "2015-07-30 16:02:52.486324", "rc": 1, "start": "2015-07-30 16:02:51.983801"}
stderr: Traceback (most recent call last):
  File "easymode-setup.py", line 40, in <module>
    'value': 'false'
  File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 223, in put
    return self.sendRestRequest('PUT', path, parameters, data=data)
  File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 214, in sendRestRequest
    text=result.text)
girder_client.HttpError: HTTP error 400: PUT http://localhost:9000/api/v1/system/setting?key=romanesco.require_auth&value=false

FATAL: all hosts have already failed -- aborting
```

**Comment by jeffbaumes** [comment]
Running `vagrant provision` after this error seems to now get past this - are we not waiting quite long enough for girder to spin up and be ready for requests like this? Or is it something about plugin initialization?

**Comment by jeffbaumes** [comment]
Also needed to do a `sudo start romanesco` while ssh'd into the vagrant machine, but then things did work as expected and I was able to run an analysis.

**Comment by jeffbaumes** [comment]
@zachmullen ideas for a fix for my first comment?

**Comment by zachmullen** [comment]
Doing a fresh `vagrant up` to see if I can reproduce the error you saw.

**Comment by zachmullen** [comment]
It doesn't look like it's not waiting long enough for the restart, I moved it down to near the end of the script and it still failed. I actually think the girder restart isn't succeeding at all, I am going to try running with more verbosity to figure out why. Might be a general problem with our handlers if the romanesco restart is also not working.

**Comment by zachmullen** [comment]
Figured out why our handlers weren't being invoked as we expected: http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change

> These ‘notify’ actions are triggered at the end of each block of tasks in a playbook, and will only be triggered once even if notified by multiple different tasks.

**Comment by jeffbaumes** [comment]
Ah yes I have been bit by this before.

**Comment by zachmullen** [comment]
@jeffbaumes that last commit fixed the issue for me

**Comment by curtislisle** [comment]
This may be unrelated, but I still generally need to restart romanesco and girder whenever I start an existing  TangeloHub instance after a vagrant halt.  The upstart daemons often don't get kicked off.  Generally I am able to provision a new instance successfully, but it has been about a month since I've made a totally new provisioning.

**Comment by curtislisle** [comment]
Ansible is amazing.  Not as amazing as you two, but amazing, nonetheless...

**Comment by zachmullen** [comment]
This has conflicts with #149 , I will merge manually

**Comment by zachmullen** [comment]
All set after a fresh `vagrant up`.

**Comment by jeffbaumes** [comment]
Alright LGTM!

**Pull request merged**
