### PR TITLE
Enable read-only view of workflow diagrams

### PR DESCRIPTION
**Pull request by zackgalbreath**
With this commit, you will no longer be able to modify a workflow unless you've enabled write access.

### CODE REVIEW

**Comment by zackgalbreath** [comment]
This addresses #81

**Comment by jeffbaumes** [comment]
@zackgalbreath I updated the app logic a little so editable state changes with the Edit button (required full reset of the view when editable changes but I think that's ok), see my latest commit. I see that connections can be made only when in edit mode, as well as step deletion, which is good. Please also disallow moving workflow components when not editable.

**Comment by zackgalbreath** [comment]
@jeffbaumes, PTAL & let me know if this PR needs any more tweaks before merging.

**Comment by jeffbaumes** [comment]
LGTM :balloon:

**Pull request merged**
